site_name: PHN CRM Help Centre

theme: readthedocs
extra_css: 
    - ../css/extra.css

nav:
- Home: 'index.md'
- Overview: 'overview.md'
- FAQ: 'faq.md'
- Entities: 
    - Account: 'entities/account.md'
    - Activity Category: 'entities/activity-category.md'
    - Agreement: 'entities/agreement.md'
    - Appointment: 'entities/appointment.md'
    - Call: 'entities/call.md'
    - Contact: 'entities/contact.md'
    - Contact Role: 'entities/contact-role.md'
    - Contact Role Type: 'entities/contact-role-type.md'
    - Controlled Document: 'entities/controlled-document.md'
    - CPRA: 'entities/cpra.md'
    - Definition: 'entities/definition.md'
    - Device: 'entities/device.md'
    - Device Allocation: 'entities/device-allocation.md'
    - Email: 'entities/email.md'
    - EULA: 'entities/eula.md'
    - Geographical: 'entities/geo/geo-overview.md'
        - Overview: 'entities/geo/geo-overview.md'
        - CED: 'entities/geo/ced.md'
        - GCC: 'entities/geo/gcc.md'
        - LGA: 'entities/geo/lga.md'
        - PHN: 'entities/geo/phn.md'
        - POA: 'entities/geo/poa.md'
        - SA1: 'entities/geo/sa1.md'
        - SA2: 'entities/geo/sa2.md'
        - SA3: 'entities/geo/sa3.md'
        - SA4: 'entities/geo/sa4.md'
        - SED: 'entities/geo/sed.md'
        - SSC: 'entities/geo/ssc.md'
        - STE: 'entities/geo/ste.md'
    - Legislation: 'entities/legislation.md'
    - Marketing List: 'entities/marketing-list.md'
    - Risk: 'entities/risk.md'
    - Risk Action: 'entities/risk-action.md'
    - Software: 'entities/software.md'
    - Software License: 'entities/software-license.md'
    - Software Allocation: 'entities/software-allocation.md'
    - Task: 'entities/task.md'
    - User: 'entities/user.md'
- Components: 'components.md'
- Tracking Activity:
    - Dynamics 365 App for Outlook: 'tracking/activity-tracking.md'
    - Activity Tracking: 'tracking/activity-tracking.md'
- Extra Features: 'extra-features.md'
- Versioning: 'versioning.md'
- Roadmap: 'roadmap.md'

markdown_extensions:
    - toc:
        permalink: "#"
