site_name: PHN CRM Help Centre

theme: readthedocs
extra_css: 
    - ../css/extra.css

nav:
- Home: 'index.md'
- Overview: 'phn-in-a-box/overview.md'
- Components: 'phn-in-a-box/components.md'
- Tracking Activity:
    - Activity Tracking: 'phn-in-a-box/activity-tracking.md'
    - Extra Features: 'phn-in-a-box/extra-features.md'
- Roadmap:
- Versioning: 'versioning.md'

markdown_extensions:
    - toc:
        permalink: "#"
